repos:
  - repo: local
    hooks:
      - id: generate-schema
        name: Generate schema
        description: Uses built-in schema generation feature to generate a schema
        language: script
        entry: .pre-commit/generate-schema
