# yaml-language-server: $schema=https://raw.githubusercontent.com/tyzbit/acars-processor/refs/heads/main/schema.json

ACARSHub:
  ACARS:
    Host: acarshub
    Port: 15550
  MaxConcurrentRequests: 0
  VDLM2:
    Host: acarshub
    Port: 15555
Annotators:
  ACARS:
    Enabled: true
    SelectedFields: null
  ADSBExchange:
    APIKey: example_key
    ReferenceGeolocation: 35.6244416,139.7753782
    SelectedFields: null
  Ollama:
    FilterWithQuestion: false
    MaxPredictionTokens: 0
    MaxRetryAttempts: 0
    MaxRetryDelaySeconds: 0
    Model: llama3.2
    Options:
    - Name: num_predict
      Value: 512
    SelectedFields: null
    SystemPrompt: Answer like a pirate
    Timeout: 0
    URL: http://ollama-service:11434
    UserPrompt: ""
  Tar1090:
    ReferenceGeolocation: 35.6244416,139.7753782
    SelectedFields: null
    URL: http://tar1090/
  VDLM2:
    Enabled: true
    SelectedFields: null
ColorOutput: true
Filters:
  ACARS:
    DuplicateMessageSimilarity: 0
  Generic:
    ASSStatus: ""
    AboveDistanceNm: 0
    AboveSignaldBm: 0
    BelowDistanceNm: 0
    BelowSignaldBm: 0
    DictionaryPhraseLengthMinimum: 0
    Emergency: false
    FlightNumber: "1234"
    Frequency: 0
    FromAircraft: false
    FromTower: false
    HasText: false
    More: false
    StationID: ""
    TailCode: "1234"
  Ollama:
    FilterOnFailure: false
    MaxPredictionTokens: 512
    MaxRetryAttempts: 0
    MaxRetryDelaySeconds: 0
    Model: llama3.2
    Options:
    - Name: num_predict
      Value: 512
    SystemPrompt: Answer like a pirate
    Timeout: 0
    URL: http://ollama-service:11434
    UserPrompt: Is there prose in this message?
  OpenAI:
    APIKey: example_key
    Model: gpt-4o
    SystemPrompt: Answer like a pirate
    Timeout: 0
    UserPrompt: Does this message talk about coffee makers or lavatories (shortand
      LAV is sometimes used)?
  VDLM2:
    DuplicateMessageSimilarity: 0
LogLevel: info
Receivers:
  DiscordWebhook:
    FormatText: true
    RequiredFields: null
    URL: https://discord.com/api/webhooks/1234321/unique_id1234
  NewRelic:
    APIKey: api_key
    CustomEventType: ""
  Webhook:
    Headers:
    - Name: APIKey
      Value: 1234abcdef
    Method: POST
    URL: https://webhook:8443/webhook/?enable_feature=yes
