# yaml-language-server: $schema=./schema.json

ColorOutput: true
LogLevel: info
ACARSHub:
  ACARS:
    Host: acarshub
    Port: 15550
  VDLM2:
    Host: acarshub
    Port: 15555
Filters:
  Ollama:
    Model: llama3.2
    URL: http://ollama-service:11434
    UserPrompt: Is there prose in this message?
Annotators:
  ACARS:
    Enabled: true
    SelectedFields:
      - acarsMessageText
      - acarsAircraftTailCode
  VDLM2:
    Enabled: true
  Tar1090:
    URL: http://tar1090
    SelectedFields:
      - tar1090AircraftDistanceMi
  Ollama:
    Model: llama3.2
    URL: http://ollama-service:11434
    UserPrompt: Is there prose in this message? If present, prose will be the last section of a message. Return any prose if found. Surround it with triple backticks.
Receivers:
  DiscordWebhook:
    URL: https://discord.com/api/webhooks/1234321/unique_id1234
    FormatText: true
