# yaml-language-server: $schema=https://raw.githubusercontent.com/tyzbit/acars-processor/refs/heads/main/schema.json

# See config_all_options.yaml for everything you can set here as well as
# more information about each setting.
ACARSProcessorSettings:
  Database:
    Enabled: true
    SQLiteDatabasePath: ./messages.db
    Type: sqlite
  ACARSHub:
    # One or more of these must be enabled in order to process messages
    ACARS:
      Host: &ac acarshub
      Port: 15550
    VDLM2:
      Host: *ac
      Port: 15555

# Each step here will be run in sequence. You can filter, annotate and send
# to a receiver all in one step if you wish.
Steps:
  - Filter:
      Builtin:
        HasText: true
        PreviousMessageSimilarity:
          Similarity: 0.9
  - Filter: {Builtin: {DictionaryPhraseLengthMinimum: 2}}
  - Filter: {Builtin: {FreetextTermPresent: true}}
  - Annotate:
      Tar1090:
        URL: http://tar1090
        ReferenceGeolocation: 50,50
  - Filter:
      Builtin:
        FilterOnFailure: false
        BelowDistanceMi: 100.0
  - Filter:
      Ollama:
        Model: &ollamamodel qwen3:30b-a3b
        URL: &ollamaurl http://ollama:11434
        FilterOnFailure: true
        MaxRetryAttempts: 1
        MaxRetryDelaySeconds: 5
        Timeout: 30
        Options: &ollamaopts [
          {Name: num_predict, Value: 150}, # Maximum number of tokens (words, kinda) to generate
          {Name: temperature, Value: 0.4}, # Creativity (0.0-2.0)
          {Name: top_p, Value: 0.2}, # Answer diversity with top_k (0.0-1.0)
          {Name: top_k, Value: 20}, # Answer diversity (ex 0-100)
          {Name: frequency_penalty, Value: 1.1}, # Penalize repeated tokens (0-2.0)
          {Name: num_gpu, Value: 40}, # Number of layers to offload to GPU
        ]
        UserPrompt:  Does this message mention lavatories (shorthand LAV)?
  - Annotate:
      SelectedFields:
        - ACARSProcessor.ACARSDramaTailNumberLink
        - ACARSProcessor.AircraftDistanceMi
        - ACARSProcessor.AircraftGeolocation
        - ACARSProcessor.FrequencyMhz
        - ACARSProcessor.From
        - ACARSProcessor.ImageLink
        - ACARSProcessor.PhotosLink
        - ACARSProcessor.SignalLeveldBm
        - ACARSProcessor.TailCode
        - ACARSProcessor.ThumbnailLink
        - ACARSProcessor.TrackingLink
        - ACARSProcessor.TranslateLink
  - Send:
      Discord:
        Embed: true
        EmbedColorFacetFields: [TailCode]
        URL: "${acars_discord_webhook}"
        FormatText: true
        FormatTimestamps: true
